/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PokemonTCGPocketExpansionsV5Schema = {
  /**
   * Expansion identifier (e.g. 'a1', 'a1a', 'pa').
   */
  id: string;
  /**
   * Display name of the expansion.
   */
  name: string;
  /**
   * ISO 8601 release date (YYYY-MM-DD), or null for promo sets.
   */
  release_date: string | null;
  /**
   * Total number of cards in the expansion.
   */
  total_cards: number;
  /**
   * URL to the full (pretty-printed) card JSON for this expansion.
   */
  cards_url: string;
  /**
   * URL to the minified card JSON for this expansion.
   */
  cards_url_min: string;
  /**
   * URL to the core variant shard for this expansion.
   */
  cards_core_url: string;
  /**
   * URL to the minified core variant shard for this expansion.
   */
  cards_core_url_min: string;
  /**
   * URL to the core no-image variant shard for this expansion.
   */
  cards_core_no_image_url: string;
  /**
   * URL to the minified core no-image variant shard for this expansion.
   */
  cards_core_no_image_url_min: string;
  /**
   * URL to the gameplay variant shard for this expansion.
   */
  cards_gameplay_url: string;
  /**
   * URL to the minified gameplay variant shard for this expansion.
   */
  cards_gameplay_url_min: string;
  /**
   * URL to the gameplay no-image variant shard for this expansion.
   */
  cards_gameplay_no_image_url: string;
  /**
   * URL to the minified gameplay no-image variant shard for this expansion.
   */
  cards_gameplay_no_image_url_min: string;
  /**
   * URL to the collection variant shard for this expansion.
   */
  cards_collection_url: string;
  /**
   * URL to the minified collection variant shard for this expansion.
   */
  cards_collection_url_min: string;
  /**
   * URL to the collection no-image variant shard for this expansion.
   */
  cards_collection_no_image_url: string;
  /**
   * URL to the minified collection no-image variant shard for this expansion.
   */
  cards_collection_no_image_url_min: string;
  /**
   * URL to the full no-image variant shard for this expansion.
   */
  cards_no_image_url: string;
  /**
   * URL to the minified full no-image variant shard for this expansion.
   */
  cards_no_image_url_min: string;
  /**
   * @minItems 1
   */
  packs: [
    {
      /**
       * Pack identifier (e.g. 'a1-charizard', 'pa-promov1').
       */
      id: string;
      /**
       * Display name of the pack.
       */
      name: string;
      /**
       * URL to the WebP pack image.
       */
      image: string | null;
      /**
       * URL to the PNG pack image.
       */
      image_png: string | null;
    },
    ...{
      /**
       * Pack identifier (e.g. 'a1-charizard', 'pa-promov1').
       */
      id: string;
      /**
       * Display name of the pack.
       */
      name: string;
      /**
       * URL to the WebP pack image.
       */
      image: string | null;
      /**
       * URL to the PNG pack image.
       */
      image_png: string | null;
    }[]
  ];
}[];
